### ISSUE TITLE
Adding Version Number to the Notebook Snippets

### ISSUE THREAD

**Issue by AbeOmor** [Azure/azureml-web#10]
Currently, customers don't know what version of the SDK the SNippets are for.

How about if we put SDK version into the snippet like this:
 
"Import Workspace": {
"prefix": ["import-workspace"],
"body": [
"from azureml.core import Workspace",
"$0"
],
"description": "Import Workspace class",
"python_sdk_version": "1.1.18"
},

**Comment by lostmygithubaccount** [comment]
i don't think our snippets should need to be versioned

**Comment by AbeOmor** [comment]
@lostmygithubaccount  What happens with a syntax change in the SDK and the user has an older version on the SDK installed?

**Comment by AbeOmor** [comment]
Since SDK shouldn't have much breaking changes, this is not needed
