### ISSUE TITLE
[Cheatsheet] Distributed training guide updates

### ISSUE THREAD

**Issue by mx-iao** [Azure/azureml-web#31]
## Details: 
- update PyTorch guide to use PyTorch job instead of MPI workaround

**Comment by mx-iao** [comment]
< assign to me >

**Comment by aminsaied** [comment]
We'll still need to include the workaround for folks using the older SDK - or at least state clearly that this is only available in SDK >=1.22 (or whatever it is).

**Comment by mx-iao** [comment]
Yep for per-process launch I'll make sure to call out the SDK version. I can also create an Archive section at the bottom of the guide to keep the MPI workaround for now.
